#!/bin/bash

echo "=== AI Agent Plugin Keyboard Debug Helper ==="
echo ""

echo "This script will help you debug the Ctrl+Alt+A keyboard shortcut issue."
echo ""

echo "1. First, let's check if the mod is properly installed:"
./check-install.sh

echo ""
echo "2. Debugging steps:"
echo ""
echo "   a) Start Oxygen Not Included"
echo "   b) Enable the AI Agent Plugin mod"
echo "   c) Start a new game or load existing save"
echo "   d) Wait 5-10 seconds for the plugin to initialize"
echo "   e) Look for these log messages in the game console:"
echo "      - '[AI Agent Plugin] GameClock initialized - AI Agent is ready'"
echo "      - '[AI Agent Plugin] Testing UI system...'"
echo "      - 'Testing UI system - if you see this, the plugin is working'"
echo ""
echo "   f) After 5 seconds, the Agent Control dialog should automatically open"
echo "      (this tests if the UI system is working)"
echo ""
echo "   g) Try pressing Ctrl+Alt+A to open the dialog manually"
echo ""
echo "3. If the automatic test dialog doesn't appear:"
echo "   - Check the game console for error messages"
echo "   - Make sure the mod is enabled in the mods menu"
echo "   - Try restarting the game"
echo ""
echo "4. If the automatic test works but Ctrl+Alt+A doesn't:"
echo "   - Try different key combinations:"
echo "     * Left Ctrl + Left Alt + A"
echo "     * Right Ctrl + Right Alt + A"
echo "     * Left Ctrl + Right Alt + A"
echo "     * Right Ctrl + Left Alt + A"
echo "   - Check if other mods might be intercepting the keys"
echo "   - Try running the game in windowed mode"
echo ""
echo "5. Alternative activation methods:"
echo "   - Look for an 'AI' button in the game UI"
echo "   - Check if the button appears in the top-left or top-right corner"
echo ""
echo "6. Common issues and solutions:"
echo "   - If you see 'Error in keyboard input' in logs: Input system conflict"
echo "   - If you see 'Error showing agent control dialog': UI system issue"
echo "   - If no logs appear at all: Mod not loading properly"
echo ""
echo "7. To get more detailed logs:"
echo "   - Enable debug mode in the game"
echo "   - Check the game's log file for '[AI Agent Plugin]' messages"
echo ""
echo "8. Test commands you can run in the game console (if available):"
echo "   - Look for any error messages starting with '[AI Agent Plugin]'"
echo ""

echo "=== Quick Test ==="
echo "After starting the game, you should see:"
echo "✓ Plugin initialization messages"
echo "✓ UI system test after 5 seconds"
echo "✓ Agent Control dialog opening automatically"
echo "✓ Ctrl+Alt+A working for manual activation"
echo ""

echo "If any of these fail, check the game console for error messages."
echo "The most common issue is that the Game.Update method isn't being called"
echo "or there's a conflict with the game's input handling system."
